### ISSUE TITLE
Control on android 9

### ISSUE THREAD

**Issue by xcoress** [aarcangeli/Serious-Sam-Android#12]
On Android 9, touch control and gyroscope does not work. So the people write.

**Comment by K0CM0HABT** [comment]
I have android 9 and touch control with gyroscope fork fine

**Comment by aarcangeli** [comment]
I never tested on android 9 and I don't have a Pixel 2.
@xcoress What exactly happens?
The stick is not shown on the screen?
Is the stick shown on the screen?
Does the stick produce effects?

**Comment by xcoress** [comment]
@aarcangeli This:![](https://i.imgur.com/RGJblo0.jpg)

**Comment by aarcangeli** [comment]
ok, touch controls are not shown.
Maybe I know why.

Touch controls are automatically displayed and hidden when you connect or disconnect a real controller (such as the xbox 360 controller) to the device.
In this case the app thinks there is a controller connected, but it is false.
I will add an option so you can force visibility.

**Comment by aarcangeli** [comment]
Fixed in 1.04.0
