### ISSUE TITLE
Single campaign from The First Encounter

### ISSUE THREAD

**Issue by K0CM0HABT** [aarcangeli/Serious-Sam-Android#13]
https://youtu.be/OJ1uL66epNM

**Comment by aarcangeli** [comment]
Good job, how did you do this?

**Comment by K0CM0HABT** [comment]
@aarcangeli guy from 4pda use in-game editor and port this
Download: https://yadi.sk/d/-XmByxKgLxIU3g (but this is not final version)
Unpack content from fusion dlc folder to SeriousSam folder, replace if needed. In game open Single Player -> Custom Level load Hatshepsut
