### ISSUE TITLE
Glitches present on some devices

### ISSUE THREAD

**Issue by aarcangeli** [aarcangeli/Serious-Sam-Android#14]
![56441151-8f334900-6305-11e9-93ee-482a57802815](https://user-images.githubusercontent.com/538137/56476291-e1a36f80-6495-11e9-85b1-ccb6c55e7c72.png)
![56441067-2e0b7580-6305-11e9-8f58-ab16a6bc16aa](https://user-images.githubusercontent.com/538137/56476292-e1a36f80-6495-11e9-92fa-6b2e262b3b19.png)

devices on which it was found:
- Mali-T720

**Comment by WatafffRu** [comment]
Thank you VERY much for paying attention to this bug. I am extremely grateful, I wait for new versions of port from you.

**Comment by WatafffRu** [comment]
And Yes, such question: in the following versions it can be corrected?

**Comment by aarcangeli** [comment]
Hi, it depends from the problem.

I can't reproduce the error so I need your help.
In [this folder](https://drive.google.com/drive/folders/1OxM81d5wZB2zzxZXR-bvcAHMrhftVipZ) there are 4 variant of this port, I'm focusing on changes made from 1.02.1 to 1.03.0.
What I ask you is to download and install them one at a time and report me the effect.
If you can, attach a screenshot of each test.

I also need SeriousSam.log (just one).

**Comment by WatafffRu** [comment]
I played on the previous version - 1.02.1 and everything was fine with textures, but fps was four times less. And what about the log - as soon as I understand how to get it, be sure to send you.

**Comment by aarcangeli** [comment]
I need you run every apk from that folder.
This is the procedure you should do:
1. Install one apk file from [this folder](https://drive.google.com/drive/folders/1OxM81d5wZB2zzxZXR-bvcAHMrhftVipZ)
1. Run the game
1. Skip introduction (you will be in the first level)
1. Attach a screenshot here
1. Repeat with the other apk files.

**Comment by WatafffRu** [comment]
Хорошо, сейчас сделаю.

**Comment by WatafffRu** [comment]
![Screenshot_2019-04-22-18-24-00](https://user-images.githubusercontent.com/49827188/56508095-8765e580-654d-11e9-9479-8e95c87c9dc8.png)
The first APK did not start, it flew. And here is a screenshot of the second. I'll send the third and fourth.

**Comment by WatafffRu** [comment]
![Screenshot_2019-04-22-18-29-30](https://user-images.githubusercontent.com/49827188/56508442-79649480-654e-11e9-9d61-7cbeb5ddf9a1.png)
this is the third APK

**Comment by WatafffRu** [comment]
And the fourth APK, it crashes at the loading stage. That's all.

**Comment by aarcangeli** [comment]
The crashes are pretty strange, I tested every package and they was good.
I have added 2 more tests:

- SeriousSam-issue-14-test-04-3f28549-release.apk
- SeriousSam-issue-14-test-05-a594107-release.apk

**Comment by WatafffRu** [comment]
пн, 22 апр. 2019 г. в 23:55, Alessandro Arcangeli <notifications@github.com

**Comment by WatafffRu** [comment]
![Screenshot_2019-04-23-10-06-41](https://user-images.githubusercontent.com/49827188/56573580-9f8c4200-65eb-11e9-959d-a98df685549e.png)
![Screenshot_2019-04-23-09-58-38](https://user-images.githubusercontent.com/49827188/56573584-a1ee9c00-65eb-11e9-80e6-2df12d9c9008.png)
here are the two versions

**Comment by aarcangeli** [comment]
Good, now I know exactly the commit that introduced this glitches.
I'll build new tests, I know it's boring for you, but I don't see other ways.

**Comment by aarcangeli** [comment]
Hi, I've added some tests.
These should be the last (I hope).

- SeriousSam-issue-14-test-06-basic.apk
- SeriousSam-issue-14-test-07-basic.apk
- SeriousSam-issue-14-test-08-disableProfiling.apk
- SeriousSam-issue-14-test-09-gles2.apk

**Comment by WatafffRu** [comment]
Well, as will the time I just check on them.

**Comment by WatafffRu** [comment]
In 09 do not work

вт, 23 апр. 2019, 23:29 Alessandro Arcangeli <notifications@github.com>:

**Comment by WatafffRu** [comment]
![Screenshot_2019-04-24-14-23-27](https://user-images.githubusercontent.com/49827188/56657517-6bd01b80-66c2-11e9-875d-40ba7cec40e1.png)
![Screenshot_2019-04-24-14-20-59](https://user-images.githubusercontent.com/49827188/56657523-6ffc3900-66c2-11e9-9367-8b01dbfb06e8.png)
![Screenshot_2019-04-24-14-15-05](https://user-images.githubusercontent.com/49827188/56657527-725e9300-66c2-11e9-933a-5253c5e6b507.png)
Version 07 sorry I can't send

**Comment by xcoress** [comment]
not comforting...

**Comment by aarcangeli** [comment]
can you check if the bug persists with the latest version?

**Comment by WatafffRu** [comment]
I answered very late, but on version 1.04 the bug is still present.

вс, 19 мая 2019 г. в 07:31, Alessandro Arcangeli <notifications@github.com>:

**Comment by aarcangeli** [comment]
In really don't know what to do with this bug, I think it is a problem of your device.

**Comment by WatafffRu** [comment]
Hey. On the new device, your port of a serious sam gives the following
error: Fatal error. Not enough memory. Can you tell me what to do?
Here is a screenshot



пт, 23 авг. 2019 г., 4:18 Alessandro Arcangeli <notifications@github.com>:
