### ISSUE TITLE
Online server

### ISSUE THREAD

**Issue by paoloans** [aarcangeli/Serious-Sam-Android#16]
I love this game but i want play the online there is possibility to play.

**Comment by aarcangeli** [comment]
Multiplayer mode is not ported.
I was already thinking of implementing it.
The problem is that you probably won't be able to play between android and computer.

**Comment by K0CM0HABT** [comment]
@aarcangeli some people play from the phone in cs1.6 and quake 3 on pc servers against pc players.:grinning:

If you do this in the future, it will be very cool, I would like to play in co-op mode

**Comment by aarcangeli** [comment]
Conversation merged in #33
