### ISSUE TITLE
Bug with color in latest version MALI T720

### ISSUE THREAD

**Issue by Skyrimus** [aarcangeli/Serious-Sam-Android#22]
I compiled latest version of apk and have some problems with color, all features have green color and it make some noise and fps drop to 3 fps, all text have green color, how to fix it? In your last build all works, why my build is broken?
![Screenshot_20190810-161026](https://user-images.githubusercontent.com/5832920/62822273-b7cba100-bb89-11e9-8ab7-4090c6897bce.png)
![Screenshot_20190810-160459](https://user-images.githubusercontent.com/5832920/62822274-b7cba100-bb89-11e9-9ce8-09ce2fac3994.png)
![Screenshot_20190810-160512](https://user-images.githubusercontent.com/5832920/62822275-b7cba100-bb89-11e9-84b9-f76a9531b8c5.png)
![Screenshot_20190810-160823](https://user-images.githubusercontent.com/5832920/62822276-b8643780-bb89-11e9-8ce4-63ea8d3f5d63.png)

**Comment by Skyrimus** [comment]
Problem solved when i compiled release apk

**Comment by aarcangeli** [comment]
The problem seems to affect only the debug build, but I think it should be fixed.
I'm working on it.

**Comment by Skyrimus** [comment]
I know, hmm, i m closed this issue already?

**Comment by Skyrimus** [comment]
@aarcangeli If use anisotropic filtration it give some artefacts, i think trouble in shader (?)

**Comment by Skyrimus** [comment]
![Screenshot_20190822-184935](https://user-images.githubusercontent.com/5832920/63529596-949bdc80-c50d-11e9-8780-2c9f93d1544f.png)
![Screenshot_20190822-184839](https://user-images.githubusercontent.com/5832920/63529597-949bdc80-c50d-11e9-85ce-06e05250fdf2.png)
![Screenshot_20190822-184853](https://user-images.githubusercontent.com/5832920/63529598-95347300-c50d-11e9-9e3a-f9f0c28bd3e2.png)

This is on more arm and intel gpus

**Comment by aarcangeli** [comment]
I don't know why but with ndk r19 it works fine.
You need to download it from [here](https://developer.android.com/ndk/downloads/older_releases.html) and update local.properties.
