### ISSUE TITLE
Custom resolution

### ISSUE THREAD

**Issue by StRawlings** [aarcangeli/Serious-Sam-Android#25]
Any possible plans for that? Game autostarts at half the resolution of my tablet (512 x 300), would like to change that. Along with the crosshair changeability, but that's a bit different topic.
The game does recognise my resolution normally, but scales it down nevertheless
![Screenshot_2019-08-17-19-50-47](https://user-images.githubusercontent.com/54215497/63214989-94c06480-c128-11e9-87ab-4ba2841fde97.png)
![Screenshot_2019-08-17-20-09-08](https://user-images.githubusercontent.com/54215497/63215142-e79b1b80-c12a-11e9-88a4-54360c2f2703.png)

**Comment by Skyrimus** [comment]
This is not bug

**Comment by Skyrimus** [comment]
Just some wrong calculation

**Comment by Skyrimus** [comment]
Maybe you need this? Normally? 
![Screenshot_20190819-184544](https://user-images.githubusercontent.com/5832920/63279767-48089500-c2b2-11e9-93d1-75ae1641111e.png)

**Comment by StRawlings** [comment]
Come on, do I really need to post in-game screenshots to show you that it ACTUALLY runs at 512 x 300? You can count pixels even on the menu screenshot

**Comment by StRawlings** [comment]
You cant tell me this is what 1024 x 600 looks like
![Screenshot_2019-08-19-19-08-57](https://user-images.githubusercontent.com/54215497/63281339-2826a080-c2b5-11e9-9024-4b876241da11.png)
![Screenshot_2019-08-19-19-08-26](https://user-images.githubusercontent.com/54215497/63281340-28bf3700-c2b5-11e9-9cc7-7ea0a0c91576.png)
![Screenshot_2019-08-19-19-05-33](https://user-images.githubusercontent.com/54215497/63281344-28bf3700-c2b5-11e9-8790-5915d1c3b232.png)

**Comment by Skyrimus** [comment]
This is not 512 x 300, i can show you it now

**Comment by Skyrimus** [comment]
Can you tell me your screen resolution and device name?

**Comment by StRawlings** [comment]
1024 x 600
Lenovo TB3-710F
Android 5.0.1

**Comment by Skyrimus** [comment]
Try now full resolution, only armv7 
[app-release.zip](https://github.com/aarcangeli/Serious-Sam-Android/files/3516859/app-release.zip)

**Comment by Skyrimus** [comment]
I wait your answer

**Comment by StRawlings** [comment]
Works like a charm! Thanks a lot!
![Screenshot_2019-08-19-20-05-55](https://user-images.githubusercontent.com/54215497/63284726-dda92200-c2bc-11e9-90f8-e67ff40dfa56.png)
![Screenshot_2019-08-19-20-05-44](https://user-images.githubusercontent.com/54215497/63284728-dda92200-c2bc-11e9-98b2-08c3264cc61b.png)

**Comment by Skyrimus** [comment]
Close later, i want to change some things to get feature to change resolution scale

**Comment by Skyrimus** [comment]
@aarcangeli Please help me with this feature https://github.com/Skyrimus/Serious-Sam-Android/commit/6f2a856400eb6a60e6a793aafc46e44f1a766227
I want to use scale variable from MainActivity in SeriousSamSurface, but it not works, check it please, maybe can fix it

**Comment by Skyrimus** [comment]
Need import scale value from MainActivity to SeriousSamSurface

**Comment by Skyrimus** [comment]
FIXED https://github.com/aarcangeli/Serious-Sam-Android/pull/24/commits/a173797d166a665b6a38e0ecbe0f71e381f30b13
