### ISSUE TITLE
Error with memory.

### ISSUE THREAD

**Issue by MrJasonRus** [aarcangeli/Serious-Sam-Android#3]
Hello!
 I did use your programm "Serious Sam Android". So, the programm is brilliant, but on my phone (Samsung Galaxy Note 5). Emulator has said that "ERROR: Not enough memory (805306624 bytes needed)!". There is a log file:
[SeriousSam.log](https://github.com/aarcangeli/Serious-Sam-Android/files/3087897/SeriousSam.log)
 I hope you would help me.

**Comment by MrJasonRus** [comment]
And what about support any another controller or keyboard with mouse? I have controllers from SplitFish like https://www.ebay.com/itm/SplitFish-FragFX-Shark-PS4-Sony-offiziell-lizenziert-PS4-PS3/254201548694?hash=item3b2f97cf96:g:kXYAAOSwa7RctaMC
There are two modes: joystick and keyboard. I understand why joystick mode not works(Because this is for playstation 3), but i dont understand why keyboard mode is not working.

**Comment by aarcangeli** [comment]
I think there is something wrong with your game directory (sdcard/SeriousSam).
What files did you put in?
The directory should contains just this files:
* SE1_00.gro
* SE1_00_Extra.gro
* SE1_00_ExtraTools.gro
* SE1_00_Levels.gro
* SE1_00_Logo.gro
* SE1_00_Music.gro
* 1_04_patch.gro
* 1_07_tools.gro

**Comment by MrJasonRus** [comment]
@aarcangeli I have these files and folder "levels".

**Comment by aarcangeli** [comment]
It is definitely a data problem.

This lines are extracted from your log:

	/storage/emulated/0/SeriousSam/SE1_00_Texts.gro: 262 files
	/storage/emulated/0/SeriousSam/SE1_00_Sounds.gro: 100 files
	/storage/emulated/0/SeriousSam/SE1_00_Music.gro: 43 files
	/storage/emulated/0/SeriousSam/SE1_00_ExtraTools.gro: 1044 files
	/storage/emulated/0/SeriousSam/SE1_00_Extra.gro: 107 files
	/storage/emulated/0/SeriousSam/SE1_00.gro: 3142 files
	/storage/emulated/0/SeriousSam/1_07_tools.gro: 18 files
	/storage/emulated/0/SeriousSam/1_04_patch.gro: 1 files

These instead are extracted from mine:

	/storage/emulated/0/SeriousSam/SE1_00_Music.gro: 43 files
	/storage/emulated/0/SeriousSam/SE1_00_Logo.gro: 1 files
	/storage/emulated/0/SeriousSam/SE1_00_Levels.gro: 49 files
	/storage/emulated/0/SeriousSam/SE1_00_ExtraTools.gro: 1044 files
	/storage/emulated/0/SeriousSam/SE1_00_Extra.gro: 107 files
	/storage/emulated/0/SeriousSam/SE1_00.gro: 3142 files
	/storage/emulated/0/SeriousSam/1_07_tools.gro: 18 files
	/storage/emulated/0/SeriousSam/1_04_patch.gro: 1 files

So you are using a different version of game data.

To use this port you have to take the game files from "Serious Sam Classic The Second Encounter"
If you don't own it, consider buying it from [steam](https://store.steampowered.com/app/41060/Serious_Sam_Classic_The_Second_Encounter/)

**Comment by MrJasonRus** [comment]
@aarcangeli but why another smartphone have similar files and works when my phone dont work. OK, i will try an another .gro files from steam.

**Comment by Thanadrax** [comment]
Might be fixed with removing texts gro, works for me.

**Comment by MrJasonRus** [comment]
@Thanadrax thank you. Now works.

**Comment by aarcangeli** [comment]
@Thanadrax thanks also from me
