### ISSUE TITLE
config file?

### ISSUE THREAD

**Issue by nex86** [aarcangeli/Serious-Sam-Android#31]
This is more a question than an issue.
Where is the config saved to change resolution and such?
The game runs in a very low resolution which I want to change to at least 720p.

**Comment by Skyrimus** [comment]
You can change resolution to full or half in Options - Android port options menu

**Comment by Skyrimus** [comment]
@nex86 
Latest apk in zip archive
[latest.zip](https://github.com/aarcangeli/Serious-Sam-Android/files/3654843/latest.zip)

**Comment by aarcangeli** [comment]
I close the issue for inactivity, if you have more questions please reopen it
