### ISSUE TITLE
Level don't load

### ISSUE THREAD

**Issue by ikumfer** [aarcangeli/Serious-Sam-Android#34]
I passed level "Land of Damned", on the next level game show "Loading world textures - 0%" and stop working. Please, fix it. 
Xiaomi Redmi Note 7 (3/32).

**Comment by Skyrimus** [comment]
Can you give game save file before level ending?

**Comment by Skyrimus** [comment]
@ikumfer All works fine, just use latest apk from archive with latest changes from my repository and check game cache integrity 
[latest_release.zip](https://github.com/aarcangeli/Serious-Sam-Android/files/3809365/latest_release.zip)

**Comment by ikumfer** [comment]
The same problem. Screenshot and save files. Cash download from 4pda.
[ScreenshotsAndSave.zip](https://github.com/aarcangeli/Serious-Sam-Android/files/3809810/ScreenshotsAndSave.zip)

**Comment by Skyrimus** [comment]
@ikumfer Strange, everything works for me, i tested on two devices, 1 - x86, 2 - arm(arm64)

**Comment by ikumfer** [comment]
I re-download cash. Level starts normal. Problem fix.

**Comment by Skyrimus** [comment]
@ikumfer close issue
