### ISSUE TITLE
CRC error in diff between connect Intel x86 and arm phones

### ISSUE THREAD

**Issue by Skyrimus** [aarcangeli/Serious-Sam-Android#40]

**Comment by Skyrimus** [comment]
https://github.com/Skyrimus/Serious-Sam-Android/commit/55065b8e106e855968a7f69be8eca8d7badcc082

**Comment by DoNotleaveMeAlone** [comment]
No problem just delete the file(apk/lib/(arm64-v8a) from within the apk only. Note if your device supports 64 and the other device does not support 64 only 32. Delete the file from 64 device only

**Comment by Skyrimus** [comment]
@DoNotleaveMeAlone outdated information
