### ISSUE TITLE
im have this on screenshot glitch on level scared yard

### ISSUE THREAD

**Issue by test270** [aarcangeli/Serious-Sam-Android#43]
![Screenshot_20200117_162238_com github aarcangeli serioussamandroid](https://user-images.githubusercontent.com/57315816/72624443-461d2d80-3947-11ea-868c-04a0e48c4274.jpg)

**Comment by Skyrimus** [comment]
Try last version of apk, unzip archive
[latest_apk.zip](https://github.com/aarcangeli/Serious-Sam-Android/files/4080544/latest_apk.zip)

**Comment by test270** [comment]
Im download latest version with network option and im open this map in network mode
