### ISSUE TITLE
Cheats to game

### ISSUE THREAD

**Issue by test270** [aarcangeli/Serious-Sam-Android#44]
Add to game infinite ammo code or editor maps for game

**Comment by TriTopora** [comment]
Maybe, adding new cheat needs to create patch. A map editor im think didnt
be ported.

**Comment by Skyrimus** [comment]
@test270 for new cheat - no problem

**Comment by test270** [comment]
but im need on android editor im not have PC

> @test270 for new cheat - no problem, to edit some maps use SeriousEditor from PC version

**Comment by Skyrimus** [comment]
@test270 https://github.com/Skyrimus/Serious-Sam-Android/commit/6aab3c6c362598910a7e151ac90683e8afcf9859

**Comment by Skyrimus** [comment]
@test270 new cheat added

**Comment by Skyrimus** [comment]
@test270 latest release with latest changes https://4pda.ru/forum/index.php?s=&showtopic=942755&view=findpost&p=93813008

**Comment by test270** [comment]
links for download apks not work

**Comment by Skyrimus** [comment]
@test270 register on 4pda to download it

**Comment by test270** [comment]
im click to download apks and showing error 404

**Comment by Skyrimus** [comment]
@test270 you can't download files without sign up on forum

**Comment by test270** [comment]
you can send apk on my email

**Comment by Skyrimus** [comment]
@test270 apk in zip archive
[SeriousSamRelease.zip](https://github.com/aarcangeli/Serious-Sam-Android/files/4190682/SeriousSamRelease.zip)

**Comment by test270** [comment]
im have question how spawn entities

**Comment by test270** [comment]
how spawn entity
