### ISSUE TITLE
serious sam xbox mod error

### ISSUE THREAD

**Issue by test270** [aarcangeli/Serious-Sam-Android#46]
![Screenshot_20200217_115921_com github aarcangeli serioussamandroid](https://user-images.githubusercontent.com/57315816/74648146-5f4f0f00-517d-11ea-9bfe-777b1923ed8a.jpg)

**Comment by Skyrimus** [comment]
@test270 This is not bug, because XBOX mod use some new classes in windows dll libraries and can't will be used on Android

**Comment by test270** [comment]
@Skyrimus were im can download this lib librares

**Comment by Skyrimus** [comment]
@test270 no where, because we don t have source code of this mod

**Comment by test270** [comment]
you mean mod files

**Comment by test270** [comment]
@Skyrimus you mean mod files

**Comment by Skyrimus** [comment]
@test270 Entities library source code for this mod

**Comment by test270** [comment]
im copy full bin here is link https://drive.google.com/file/d/18-m9SM63-I9mdDIQw87j9n1ed0_js9M0/view?usp=drivesdk

**Comment by test270** [comment]
@Skyrimus im copy files from bin link here
https://drive.google.com/file/d/18-m9SM63-I9mdDIQw87j9n1ed0_js9M0/view?usp=drivesdk

**Comment by Skyrimus** [comment]
@test270 I will no longer answer your questions if you do not understand the first time what we do not have the source code for the dll files from this mod, please close issue.

**Comment by test270** [comment]
why this .so files is hidden in app?

**Comment by test270** [comment]
Lol
