### ISSUE TITLE
Name and third person mode

### ISSUE THREAD

**Issue by Eight69** [aarcangeli/Serious-Sam-Android#50]
Do you will add the the possibility to modify the name of the Player (example: *Dude* instead of Player 0) and maybe add the possibility to play in third person mode, that will be awesome!

**Comment by Skyrimus** [comment]
@Eight69 It has been implemented for a long time ago. You can download latest apk with latest fixes here. 
https://ci.appveyor.com/project/aarcangeli/serious-sam-android/build/artifacts
Please close issue :)

**Comment by Eight69** [comment]
Thank you, can you please explain me how to do it? I'm a newbie XD

(I will immediately close this issue)

**Comment by Skyrimus** [comment]
@Eight69 download link https://ci.appveyor.com/api/buildjobs/cfje0reujpt244m1/artifacts/SeriousSamAndroid-v1.04.0-nightly-68b2b2a-release.apk
