### ISSUE TITLE
Changing layout of touch buttons

### ISSUE THREAD

**Issue by vimal199** [aarcangeli/Serious-Sam-Android#53]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Can you add an option for changing of layout of touch buttons?

**Comment by vimal199** [comment]
Is there a way to change the layout of touch buttons?

**Comment by Skyrimus** [comment]
Please close issue, your issue is clone of this https://github.com/aarcangeli/Serious-Sam-Android/issues/19

**Comment by vimal199** [comment]
Ok.i let's hope it will be available soon.
