### ISSUE TITLE
Problem compiling

### ISSUE THREAD

**Issue by BottomlessEmptiness** [aarcangeli/Serious-Sam-Android#57]
I'm looking to compile a version of the source code with the added feature of button mapping support (specifically Skyrimus's) because the default control scheme for my gamepad (running on Android 8.1) is unplayable. The error code is native to the original source code and if Skyrimus can see this: please upload a working APK to your version's releases so this game can be playable for people on gamepads with this issue.

$ adb shell am start -n "com.github.aarcangeli.serioussamandroid/com.github.aarcangeli.serioussamandroid.SplashScreen" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Error while executing: am start -n "com.github.aarcangeli.serioussamandroid/com.github.aarcangeli.serioussamandroid.SplashScreen" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.github.aarcangeli.serioussamandroid/.SplashScreen }
Error type 3
Error: Activity class {com.github.aarcangeli.serioussamandroid/com.github.aarcangeli.serioussamandroid.SplashScreen} does not exist.

Error while Launching activity

**Comment by Skyrimus** [comment]
Check latest release - https://github.com/Skyrimus/Serious-Sam-Android/releases/tag/v1.04.13

**Comment by BottomlessEmptiness** [comment]
Thank you!

**Comment by Skyrimus** [comment]
@BottomlessEmptiness plz close issue
