### ISSUE TITLE
Final boss crash

### ISSUE THREAD

**Issue by K0CM0HABT** [aarcangeli/Serious-Sam-Android#6]
Crash at final boss first cutscene
Quick Save: https://drive.google.com/file/d/16LcVSHbQgtRB9JoNikjx2NfWQ-ir0X6A/view?usp=drivesdk

Just run forward and watch cutscene.

**Comment by aarcangeli** [comment]
I fixed the issue, but you will need to discard your save game.

**Comment by K0CM0HABT** [comment]
@aarcangeli Okay, thanks, as u release new version I wil re-run game and check:smile_cat:

**Comment by K0CM0HABT** [comment]
@aarcangeli if u can add button for serious bomb please

**Comment by aarcangeli** [comment]
I don't know where but I'll try

**Comment by K0CM0HABT** [comment]
@aarcangeli Hi, you can compile a version with new fixes? I can continue to look for others issues and inform you about them

**Comment by aarcangeli** [comment]
I just released the new version.
Thanks for quick saves (they was very helpful)

But why were there dummies in game?

**Comment by K0CM0HABT** [comment]
@aarcangeli At your service, bro

This bug is in the PC classic version of the game
