### ISSUE TITLE
Crash on 2nd boss 2.0

### ISSUE THREAD

**Issue by K0CM0HABT** [aarcangeli/Serious-Sam-Android#9]
Just shoot in him.
Save: https://drive.google.com/file/d/1LqTMbOvPPQUPRn4SON5hrC3Pvn_kjenw/view?usp=drivesdk

This worm does not want to be killed:smile:

**Comment by K0CM0HABT** [comment]
Final boss work fine and tower of babel loading now but this thing crashing again and again

**Comment by aarcangeli** [comment]
Fixed, I really hope this is the last one.

**Comment by K0CM0HABT** [comment]
@aarcangeli if u release hotfix I can check it

**Comment by xcoress** [comment]
@K0CM0HABT Don't be in a hurry. Graphic artifacts remain on some devices.

**Comment by K0CM0HABT** [comment]
@xcoress for this u need open a new issue and give to developer catlog.txt. Without catlog this problem can not be solved because the developer does not have all the existing smartphones in this world

**Comment by K0CM0HABT** [comment]
@xcoress the developer simply will not be able to reproduce this problem if he does not have this problem

**Comment by aarcangeli** [comment]
apk released.

@xcoress be patient, one thing at a time.
And yes, please open a dedicated issue.

**Comment by K0CM0HABT** [comment]
@aarcangeli bro, you made it, this boss now can be killed. Great job:grinning:
